# Generated by Django 4.1.2 on 2022-10-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
